### PR TITLE
#250 bugfix in doubly nested field name

### PR DESCRIPTION
**Pull request by rudiedirkx**
Added `FormHelper->transformToBracketSyntax()`, which helps in fixing the field's name. It's not super pretty, but I think it handles all cases.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@rudiedirkx Thanks for the pr. can you add some tests for this? So we can be sure it works properly.

**Comment by rudiedirkx** [comment]
What would the test be? Check output name attributes? It's not really a testable feature. Give me a direction and I'll cook something up.

**Comment by kristijanhusak** [comment]
Setup that form structure in a test (Form has child form, which has another child form inside), and add checks similar to these [here](https://github.com/kristijanhusak/laravel-form-builder/blob/master/tests/FormTest.php#L635)

**Comment by rudiedirkx** [comment]
Oooh, not even with rendering into HTML? I can do that. Probably next week.

**Comment by rudiedirkx** [comment]
Or just now. Voila.

It's kinda annoying you can't run a single class: `vendor/bin/phpunit tests/FormTest.php`, because FormTest assumes the other test has run, which defines the form classes. But it's super super fast, so doesn't really matter.

How's this? Looks a bit skinny, but tests the fix exactly. Test result before fix:

```
There was 1 failure:

1) FormTest::it_has_html_valid_element_names
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'child[form][name][text]'
+'child[form][name[text]]'
```

**Comment by kristijanhusak** [comment]
I just noticed here and another PR that you are using field names like `name[text]`. Is that the only situation where you get names like this `child[form][name[text]]`, or it happens also if you add child form, that has another child form?

I'm asking this because package never supposed to manage that kind of naming. If you need that kind of naming, use a child form.

**Comment by rudiedirkx** [comment]
Child forms alone work, but a child form with nesting doesn't.

I sometimes (in my app, not really a package) use nesting like `name[text]` to group content. For instance a wysiwyg will have a `text` and `format`: `description[text]` and `description[format]`, but it's not really form worthy. Or I can have a form with dynamic inputs, like a translation for every question in the database. The form will dynamically create elements `question[<id>]`, so `question[1]`, `question[34]` etc.

All subsequent validations work fine with these doubly/mixed nesting, it was just the field name that didn't.

**Comment by kristijanhusak** [comment]
Naming of dynamically created elements should be working fine if you are using CollectionType.
Anyway, this is a good addition, but i would like to skip this double conversion if it's not really needed.
Just add a check if `$name` contains `[` or `]`, and reformat it to the proper syntax, if not, just proceed how it was.

**Comment by rudiedirkx** [comment]
I don't think that's more readable, and it won't really matter performance wise...

That would make:

```
if (strstr($this->getName(), '[') || strstr($this->getName(), ']')) {
	return $this->formHelper->transformToBracketSyntax(
		$this->formHelper->transformToDotSyntax(
			$this->getName() . '[' . $name . ']'
		)
	);
}

return $this->getName() . '[' . $name . ']';
```

I really don't like that just to save 2 ms per page... If you do, I'll fix it. Or if you know a nicer way to check if the name contains `[` or `]`.

**Comment by rudiedirkx** [comment]
I didn't know about 'collection'. That might suit better than typing `question[N]`. I'm assuming it accepts rules.

**Comment by kristijanhusak** [comment]
I agree that is not more readable, but why to do transformation it if it's not really necessary. 
I would suggest using `strpos` instead of `strstr`, as php.net says [here](http://php.net/manual/en/function.strstr.php):

> Note:
> If you only want to determine if a particular needle occurs within haystack, use the faster and less memory intensive function strpos() instead.

so something like this should work:

```php
$fieldName = $this->getName();
if (strpos($fieldName, '[') !== false || strpos($fieldName, ']') !== false) {
    return $this->formHelper->transformToBracketSyntax(
        $this->formHelper->transformToDotSyntax(
            $fieldName . '[' . $name . ']'
        )
    );
}

return fieldName . '[' . $name . ']';
```

**Comment by rudiedirkx** [comment]
Voila. Tests still good.

**Comment by kristijanhusak** [comment]
Nice, thanks!

**Pull request merged**
