### PR TITLE
add const to all types

### PR DESCRIPTION
**Pull request by tresa02**
Hello Kris
I create const in interface for Form class to easy to use fields and faster to found.
When I use this package I should check the uses field every time.
when we use const we don't need search any time for special field

this form is readable than origin Form Class:

`class SongForm extends Form {
 public function buildForm() {
 $this ->add('name', Form::FIELD_TEXT) 
->add('lyrics', Form::FIELD_TEXTAREA) 
->add('publish', Form::FIELD_CHECKBOX); }
 }`

### CODE REVIEW

**Comment by kristijanhusak** [comment]
I'd rather put this into a trait instead of an interface. Interface's purpose is not for this.

**Comment by tresa02** [comment]
thank you kris but trait can not have constants .if we should not use interface we must define constants in Form Class so the good idea is Form class must extend to another class that have this constants if you agree with me i send pull request agian.
thank you.

**Comment by tresa02** [comment]
thank you kris but trait can not have constants .if we should not use interface we must define constants in Form Class if you agree with me i send pull request agian.
thank you.

**Comment by kristijanhusak** [comment]
@tresa02 oh, i didn't know traits cannot have constants, never tried it.
I don't like the idea of putting it in the form class. We could have it as a separate class, something like this:

```php
class Field {
    const TEXT = 'text';
    const TEXTAREA = 'textarea';
}
```

and then just use it:
```php
$this->add(Field::TEXT)->add(Field::TEXTAREA)
```

**Comment by tresa02** [comment]
i fixed it 
tnx kris.

**Comment by kristijanhusak** [comment]
Thanks!

**Pull request merged**
