### PR TITLE
Drop Laravel less than 5.4

### PR DESCRIPTION
**Pull request by ukeloop**
This project doesn't support laravelcollective/html less than 5.4. 

https://github.com/kristijanhusak/laravel-form-builder/blob/ad01f1cf8eb2dd953fc4d4c9d3fa51d703d61723/composer.json#L14

### CODE REVIEW

**Comment by rudiedirkx** [comment]
I don't even know why this package registers `'form'`. `laravelcollective/html` does that, no? The order doesn't matter, because it's `register()`. Why not completely remove `registerFormIfHeeded()` and `registerHtmlIfHeeded()`?

**Comment by ukeloop** [comment]
`laravelcollective/html` is used in views.

**Comment by rudiedirkx** [comment]
> `laravelcollective/html` is used in views.

And it's a dependency, so why register it twice? `laravelcollective/html` already register it, right?

**Comment by rudiedirkx** [comment]
Tests fail without it, but that's not a reason to override a dependency's registration, AND it's easily fixable by extending `FormBuilderTestCase` to include a bit of `laravelcollective/html`:

```php
    protected function getPackageProviders($app)
    {
        return [
            'Collective\Html\HtmlServiceProvider',
            'Kris\LaravelFormBuilder\FormBuilderServiceProvider',
        ];
    }

    protected function getPackageAliases($app)
    {
        return [
            'Acme' => 'Kris\LaravelFormBuilder\Facades\FormBuilder',
            'Form' => 'Collective\Html\FormFacade',
            'Html' => 'Collective\Html\HtmlFacade',
        ];
    }
```

And then we can completely remove `registerHtmlIfNeeded()` and `registerFormIfHeeded()`.

**Review by rudiedirkx — CHANGES_REQUESTED** [review]
Add `laravelcollective/html`'s service provider and facade to the test suite, and completely remove `registerFormIfHeeded()` and `registerHtmlIfHeeded()`.

**Comment by ukeloop** [comment]
Thanks for fixing my codes. I must have missed the settings for package auto discovery.

Maybe we don't need this setup?

https://github.com/kristijanhusak/laravel-form-builder/blob/a7a93e6d78a2a9f0634b9bafb10313ec0310ce68/README.md?plain=1#L51-L68

**Comment by rudiedirkx** [comment]
My 'fix' was only for testing. You're also correct in your quote, but that's yet another issue IMO =)

If you're okay with the current code, I'm gonna merge it, because I like it.

**Comment by ukeloop** [comment]
Sure, please.

**Pull request merged**
