### PR TITLE
Change PHP keywords to comply with PSR2

### PR DESCRIPTION
**Pull request by friendlydan**
Hi, I've changed some PHP keywords to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

### CODE REVIEW

**Comment by rudiedirkx** [comment]
Were these the only uppercase true/false/null?

**Comment by mikeerickson** [comment]
@friendlydan as @rudiedirkx mentioned, it seems this PR only addresses 2 of the 15 items and not worthy of a full PR.  If you want to change them all and resubmit, that would be something we could work with.

**Comment by friendlydan** [comment]
@rudiedirkx Could you please point me in the direction of the other 13? I thought I'd caught them all sorry.

**Comment by rudiedirkx** [comment]
My 15 was a made up number. The question was a real question: are these 2 the only 2? If you've searched, and you say they are the only 2, I believe you.

Sorry for the confusion. I just meant, if you haven't searched, first search, and make sure we get all of them at once.

**Comment by mikeerickson** [comment]
@rudiedirkx lol, I guess I should have searched myself, but I was just assuming you had done that and trusted what you said.  I guess with only 2 it is not a big deal, I will go ahead and get this PR merged

**Comment by mikeerickson** [comment]
@friendlydan thanks for your PR, just merged. Surprising there were only 2 throughout the source 👍

**Pull request merged**
