### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-form-builder.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "kris/laravel-form-builder": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by rudiedirkx** [comment]
Tests pass, buttttt with Laravel 10, not 11. Maybe the test should have a version matrix for PHP + Laravel, so we can explicitly test L9, L10 and L11.

**Comment by webpioneer23** [comment]
I need this module for Laravel v11.  I tried to install the module with the above guide, but I've got error. When will this module be ready to work in laravel v11?

**Comment by rudiedirkx** [comment]
We need betters tests in [.github/workflows/test.yml](https://github.com/kristijanhusak/laravel-form-builder/blob/master/.github/workflows/test.yml). Laravel 11 isn't tested now. We need a better matrix that tests `[php 8.0, 8.1, 8.2, 8.3] x [laravel 9, 10, 11]` (with some hard-coded exceptions like L11 on P8.0). I'll give it a shot today.

**Comment by rudiedirkx** [comment]
The test matrix works, butttt all Laravel 11 tests fail. @webpioneer23 How do you feel about finding out why and fix them? :D Check out this branch, and then run `composer require illuminate/database:^11.0 illuminate/validation:^11.0` to install Laravel 11, and then run `vendor/bin/phpunit` to see what's wrong.

**Comment by hooman-mirghasemi** [comment]
I check it, if you change composer like this:

    "require-dev": {
        "orchestra/testbench": "^6.13 || ^7 || ^8 || ^9",
        "phpunit/phpunit": "^10.0.0"
    },

all of your test with laravel 11 will pass.


The issue is for PHP unite 11, if want to use PHP unite 11 you should change tests and remove all @test annotation and use test in function name with camelcase . see:
https://phpunit.de/getting-started/phpunit-11.html
and 
https://phpunit.de/announcements/phpunit-11.html
Metadata section

**Comment by rudiedirkx** [comment]
@hooman-mirghasemi Almost perfect. All we have to do now is tell the Github workflow to use phpunit 9.x for Laravel 9. More `matrix`?

**Comment by rudiedirkx** [comment]
Laravel 11 seems to work fine. And Github tests too 👍 

Thanks @hooman-mirghasemi

**Comment by hooman-mirghasemi** [comment]
your welcome
now only we need new tag (version) of this repo.

**Comment by rudiedirkx** [comment]
Voila.

**Pull request merged**
