### PR TITLE
Buttongroup

### PR DESCRIPTION
**Pull request by noxify**
Implementation for Button groups ( fix for #288 ).

Example & HTML Result are documented here:
https://github.com/kristijanhusak/laravel-form-builder/issues/288#issuecomment-263068015

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Thanks, it looks great!

**Comment by MahdiPishguy** [comment]
@noxify @jojonas 

how can we use with this feature? is there any sample code?

**Comment by noxify** [comment]
Hey @MahdiPishguy,

Unfortunately I have no examples for this since this is a 4 years old topic 🤷🏾‍♂️ 

Sorry!

**Comment by noxify** [comment]
But you could check #288 there are some examples for the button group

**Pull request merged**
