### PR TITLE
hidden function is added for Field.

### PR DESCRIPTION
**Pull request by bkayranci**
I think **hidden** function is required for fields.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Sorry but i cannot accept this. You can modify any field easily, and this is css stuff. If you need hidden value, just use input type hidden.

**Comment by bkayranci** [comment]
@kristijanhusak However I have a using like following:

> $('#image').click(function(){
> $('#inputPhoto').click();
> });

because of that, I think we should have a hidden file input instead of hidden input.

**Comment by kristijanhusak** [comment]
Just add the display none manually when creating a form. Different css doesnt mean different field type.

**Comment by bkayranci** [comment]
OK. Thank you :+1:

**Pull request closed without merging**
