### PR TITLE
Allow for form level configuration

### PR DESCRIPTION
**Pull request by beghelli**
Hi Kris, thanks for this project. Very helpful. :)

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@beghelli how you want to add a custom configuration for a form? As a property (like you did in a test), or in some other way?

I think this PR is a bit overcomplicated for such feature. We could have a `getConfig` method on a Form class, that would merge the custom configuration with the configuration read from the form helper class.

That way we could avoid injecting the custom config into the helper and handle everything on the form class.

**Comment by kristijanhusak** [comment]
You can update fields to pull the config from the parent form that is injected through constructor. 
Basically my idea is to have the config property on each class, like you added, and to have a `getConfig` on the Form class, that will merge the default config from FormHelper and the config property that you set.
After that, update all calls to formHelper->getConfig to call Form->getConfig instead.

Not sure if i explained it well, but this solution does not require doing anything in the FormBuilder and FormHelper class, and avoids those conditional form helper injections.

**Comment by beghelli** [comment]
Sure, I will give it a shot and update the pull request. Thanks!

**Comment by beghelli** [comment]
@kristijanhusak updated the pull request with your suggestions. I did one change into the FormHelper class though, but just to avoid duplicating the logic of getting the configuration. Let me know what you think, thanks.

**Comment by kristijanhusak** [comment]
@beghelli also please update all the changes to use spaces instead of tabs so it can be consistent.

**Comment by kristijanhusak** [comment]
Thanks!

**Pull request merged**
