### PR TITLE
collection input using empty_model

### PR DESCRIPTION
**Pull request by rudiedirkx**
If there's no original data, only `empty_row` data should be used, so only 1 row, AND formatted into models if `empty_model` is set.

### CODE REVIEW

**Comment by rudiedirkx** [comment]
If the collection has 0 rows, AND 'empty_row` is true:

- only use the 1st input row, not every input row
- use `formatInputIntoModels` to format input into wanted model

**Comment by rudiedirkx** [comment]
Crap. Maybe that's wrong logic. What if `prefer_input` is true, AND `empty_row` is true, and there's no input/database data? Then only `empty_row` is used, and input is cut off at index 1, so only 1 row, even if `prefer_input` is true to allow all rows.

**Comment by rudiedirkx** [comment]
This is better. Accepted data now depends on `empty_model` and `prefer_input`. @kristijanhusak Objections?

**Comment by kristijanhusak** [comment]
Looks ok to me.

**Review by kristijanhusak — APPROVED** [review]

**Pull request merged**
