### PR TITLE
Added ability to pass attributes to individual options in select/choices

### PR DESCRIPTION
**Pull request by imTigger**
Added ability to pass attributes to individual options in select/choices

For example, I want to disable certain option in my select/choice list
Pass two-dimensional array with 
['option_key' => ['attribute' => 'attribute_value']] into `option_attributes` option.

Inspired by the 5th parameter of LaravelCollective Form::select()
https://github.com/LaravelCollective/html/blob/6.x/src/FormBuilder.php#L614

Example:
```php
<?php

namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class ExampleForm extends Form
{
    public function buildForm()
    {
        $this->add('languages_select', 'select', [
            'choices' => ['en' => 'English', 'fr' => 'French', 'zh' => 'Chinese'],
            'choice_options' => [
                'wrapper' => ['class' => 'choice-wrapper'],
                'label_attr' => ['class' => 'label-class'],
            ],
            'selected' => ['en'],
            'option_attributes' => ['zh' => ['disabled' => 'disabled']],
            'expanded' => false,
            'multiple' => false
        ]);

        $this->add('languages_choice_select', 'choice', [
            'choices' => ['en' => 'English', 'fr' => 'French', 'zh' => 'Chinese'],
            'choice_options' => [
                'wrapper' => ['class' => 'choice-wrapper'],
                'label_attr' => ['class' => 'label-class'],
            ],
            'selected' => ['en'],
            'option_attributes' => ['zh' => ['disabled' => 'disabled']],
            'expanded' => false,
            'multiple' => false
        ]);

        $this->add('languages_choice_select_multiple', 'choice', [
            'choices' => ['en' => 'English', 'fr' => 'French', 'zh' => 'Chinese'],
            'choice_options' => [
                'wrapper' => ['class' => 'choice-wrapper'],
                'label_attr' => ['class' => 'label-class'],
            ],
            'selected' => ['en', 'fr'],
            'option_attributes' => ['zh' => ['disabled' => 'disabled']],
            'expanded' => false,
            'multiple' => true
        ]);

        $this->add('languages_checkbox', 'choice', [
            'choices' => ['en' => 'English', 'fr' => 'French', 'zh' => 'Chinese'],
            'choice_options' => [
                'wrapper' => ['class' => 'choice-wrapper'],
                'label_attr' => ['class' => 'label-class'],
            ],
            'option_attributes' => ['zh' => ['disabled' => 'disabled']],
            'selected' => ['en', 'fr'],
            'expanded' => true,
            'multiple' => true
        ]);

        $this->add('languages_radio', 'choice', [
            'choices' => ['en' => 'English', 'fr' => 'French', 'zh' => 'Chinese'],
            'choice_options' => [
                'wrapper' => ['class' => 'choice-wrapper'],
                'label_attr' => ['class' => 'label-class'],
            ],
            'option_attributes' => ['zh' => ['disabled' => 'disabled']],
            'selected' => ['en'],
            'expanded' => true,
            'multiple' => false
        ]);
    }
}

```

### CODE REVIEW

**Comment by rudiedirkx** [comment]
I like it. Maybe add a simple test for all types you mentioned?

**Comment by imTigger** [comment]
Sure, I haved added a test case for the new feature.
But I'm not quite if it's the best method to test against it.
Because attributes in HTML are unordered, it's difficult to test without parse the HTML again.

**Comment by rudiedirkx** [comment]
Yes, that's not great. That'll break at some point, and it'll be a bitch to debug why.

I'm sure there's a dom lib in `require-dev` somewhere. Combined with `symfony/css-selector` it's easy to check an attr on a dom element like `option[value="zh"]`. If you make a test class method `assertDomElementHasAttribute` or something it's even very readable.

**Comment by rudiedirkx** [comment]
I do like this one @imTigger. You willing to extend the test case?

**Comment by rudiedirkx** [comment]
Almost got `assertXmlStringEqualsXmlString` to work, which ignores attribute order, BUT no, it doesn't accept some HTML like `multiple` without value, or `<input>` without closing.

**Pull request merged**
