### PR TITLE
updated dependency support for laravel 8

### PR DESCRIPTION
**Pull request by juliancc**
I bumped the composer laravel dependency to allow laravel 8. 
No breaking changes were expected.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by rudiedirkx** [comment]
Damn, Laravel moves fast. I'm still on 6 I think... Does it change any between major versions? Does everything still work?

**Comment by juliancc** [comment]
> Damn, Laravel moves fast. I'm still on 6 I think... Does it change any between major versions? Does everything still work?

From their website:

Laravel and its other first-party packages follow Semantic Versioning. Major framework releases are released every six months (~February and ~August), while minor and patch releases may be released as often as every week. Minor and patch releases should never contain breaking changes.

**Comment by rudiedirkx** [comment]
Right... So does anything change? At least 2 major versions without any changes in this package. Does everything still work?

**Comment by rudiedirkx** [comment]
Automatic tests test against Laravel 6.18.40 (e.g. https://github.com/kristijanhusak/laravel-form-builder/runs/1093155207). I'm assuming someone tested 7.x and 8.x too.

**Pull request merged**
