### PR TITLE
Update CollectionType.php

### PR DESCRIPTION
**Pull request by bhcosta90**
Fix to correct one to many collect

### CODE REVIEW

**Comment by rudiedirkx** [comment]
Why? How? When? Etc. I'm very dumb. Explain to me.

**Comment by bhcosta90** [comment]
This change solved my one to many problem when I was using Form Collect, I will put the example below

```
<?php

namespace Modules\Orcamento\Forms;

use Kris\LaravelFormBuilder\Form;
use Modules\Cliente\Entities\Cliente;

class OrcamentoForm extends Form
{
    public function buildForm()
    {
        $clientes = Cliente::all()->pluck('nome', 'id')->toArray();

        $this->add('cliente_id', 'select', [
            'label' => "Cliente",
            'choices' => ["" => "Selecione..."] + $clientes,
            'rules' => [
                'required'
            ]
        ])->add('contato_id', 'select', [
            'label' => "Contato",
            'choices' => ["" => "Selecione..."],
            'attr' => [
                'disabled' => true,
            ],
        ])->add('itens', 'collection', [
            'type' => 'form',
            'property' => 'name',
            'prototype' => true,            // Should prototype be generated. Default: true
            'prototype_name' => '__NAME__', // Value used for replacing when generating new elements from prototype, default: __NAME__
            'options' => [
                'label' => false,
                'attr' => ['class' => 'tag'],
                'class' => OrcamentoItemForm::class,
            ]
        ]);
    }
}

```

```
<?php

namespace Modules\Orcamento\Forms;

use Kris\LaravelFormBuilder\Form;
use Modules\Cliente\Entities\Cliente;

class OrcamentoItemForm extends Form
{
    public function buildForm()
    {
        $this->add('nome', 'text', [
            'label' => "Nome",
        ])->add('model_id', 'hidden', [
            'label' => "Model ID",
        ])->add('model_type', 'hidden', [
            'label' => "Model Type",
        ])->add('quantidade', 'number', [
            'label' => "Quantidade",
        ])->add('preco', 'number', [
            'label' => "Preço",
        ]);
    }
}

```

Before he only saved the first item, with my change he will save all the items in the array.

**Comment by rudiedirkx** [comment]
Looks like a config error, not a package bug. The whole point of the Collection is to save more items, so it'd be very strange if it never did. Everyone would be complaining about this.

I'll explain, because the docs are still not good enough (and I'm still too lazy):

- ALWAYS build the form in the POST action (save) like you built it in the GET action (show form). That means the same model, the same data, the same parameters. Everything exactly the same. That way, the form validator knows how many items to validate & accept.
- If your POST data can contain more items than the GET form (e.g. because you add items with JS), set the `collection` config `prefer_input => true`.

I think the first applies to you, not the second. If that doesn't work, show me the controller actions where the forms are initiated.

**Comment by rudiedirkx** [comment]
Also, why do you have a `'property' => 'name'`? Don't you want the whole child form?

**Comment by rudiedirkx** [comment]
I've FINALLY created a chapter for this in the docs. Let me know if it's not perfect: https://kristijanhusak.github.io/laravel-form-builder/field/collection.html#validated-collection-items

**Pull request closed without merging**
