### PR TITLE
+Extensible RulesParser

### PR DESCRIPTION
**Pull request by rudiedirkx**
From #340 

This allows the developer to extend the RulesParser to add their own 'rule to attribute' logic.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Maybe i'm a bit confused, but how would you extend it with this code? Can you give an example?

**Comment by kristijanhusak** [comment]
Nevermind, figured it out.

**Comment by kristijanhusak** [comment]
Thanks for the PR.

**Comment by rudiedirkx** [comment]
It's a little convoluted, but extending the FormHelper is pretty easy. Maybe a factory closure (or what does Laravel call them) would have been better, but meh.

**Pull request merged**
