### PR TITLE
#413 Multiple form in one page (More errorBag)

### PR DESCRIPTION
**Pull request by Fellner96**

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Thanks.

**Comment by HoffmannAndras** [comment]
👏

**Comment by hectnandez** [comment]
Hi,

In my application I have a several forms, but when I get the errors validation in one of them, an make a redirect back, the errors it's show it in all of them..

image

I just uptated to the version 1.6.50, but I'm still have this bug, do I miss something?

Thanks for the help.

**Comment by rudiedirkx** [comment]
I think you have to explicitly name the error bag in every distinct form:

    /**
     * Define the error bag name for the form.
     *
     * @var string
     */
    protected $errorBag = 'default';

Only for forms that are on pages with other forms.

I think.

**Pull request merged**
