### PR TITLE
Add InvalidArgumentException

### PR DESCRIPTION
**Pull request by ukeloop**

### CODE REVIEW

**Comment by Eloar** [comment]
@rudiedirkx it looks like could be merged already

**Comment by rudiedirkx** [comment]
Adding exceptions is good, but not backward compatible. I'm afraid to merge.

(I missed this PR. Weird. Sorry.)

**Comment by ukeloop** [comment]
If v2 will be released, I think it's appropriate that they be merged into V2.

**Comment by rudiedirkx** [comment]
I a gree uts

**Comment by rudiedirkx** [comment]
i agree its very v2 butb= thats nowhere near ready, and just my personal pet project (eg removing the `entity` field). Dont wait for v2

**Comment by rudiedirkx** [comment]
Let's do it.

**Pull request merged**
