### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/kristijanhusak/laravel-form-builder/pull/669/commits/13a92a0a0bb3ef1158c40049e4f324eea85800c9?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-form-builder.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "kris/laravel-form-builder": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by kristijanhusak** [comment]
@jasonmccreary it was already done as part of https://github.com/kristijanhusak/laravel-form-builder/pull/668

**Comment by rudiedirkx** [comment]
@jasonmccreary Shift's PR could be smarter/smaller. Some diffs are not diff: `8.0` in the version matrix, the `keywords` white space.

**Comment by jasonmccreary** [comment]
@rudiedirkx, yes, we have noted this change and will clean it up for next time.

**Pull request closed without merging**
