### PR TITLE
creating forms with simple arrays

### PR DESCRIPTION
**Pull request by saeidraei**
Hi
By this changes creating form will be possible without creating form classes.
I believe this changes help us to make form system that users can create costume form themselves.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@saeidraei this looks really good. Can you just add at least one test that validates the functionality. Thanks!

**Comment by rudiedirkx** [comment]
This

    ->make(Form::class)

should be updated to

    ->make($this->plainFormClass)

since cf56836.

Just protecting my interests.

@saeidraei I'd love to see how you'll be using this. UI for creating forms?

**Comment by saeidraei** [comment]
@rudiedirkx thanks for noticing the update
I haven't done it  yet but I want to do it with arrays that will be stored in json format

**Comment by hlorofos** [comment]
thanks @saeidraei outstanding job. I'm using the code from your branch, for unknown reason it wasn't merged into main repo.

**Comment by saeidraei** [comment]
@kristijanhusak i have add one test would you want to merge this ? cause i'm gonna use it.

**Comment by kristijanhusak** [comment]
@saeidraei  merged it. Thanks for the PR!

**Pull request merged**
