### PR TITLE
ChoiceType: Deal with child options

### PR DESCRIPTION
**Pull request by schursin**
Now we can set up child options, for example **size** or **VueJS attributes**.

PHP:

```
$this->add('languages', 'choice', [
    'choices' => ['en' => 'English', 'fr' => 'French'],
    'multiple' => true
]);
```

Blade:

`{!! form_row($form->languages, ['attr' => ['size' => 10, '@input' => 'update']]) !!}`

Output before:

`<select class="form-control" multiple="1" id="languages[]" name="languages[]">`

Output after:

`<select class="form-control" multiple="1" size="10" @input="update" name="languages[]">`

### CODE REVIEW

**Comment by kristijanhusak** [comment]
You should be able to achieve that by passing options through `choice_options`.
http://kristijanhusak.github.io/laravel-form-builder/field/choice.html

**Comment by schursin** [comment]
Now:

`{!! form_row($form->languages, ['child_options' => ['attr' => ['size' => 10, '@input' => 'update']]]) !!}`

**Comment by kristijanhusak** [comment]
@schursin no, my point is that you should be able to already do that, since merging is done in the class here https://github.com/kristijanhusak/laravel-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/ChoiceType.php#L101

**Comment by schursin** [comment]
@kristijanhusak checked that, not working

Template:

`form_row($form->languages, ['child_options' => ['attr' => ['size' => 10, '@input' => 'update']]])`

HTML:

`<select class="form-control" multiple="1" id="languages[]" name="languages[]">`

**size** attribute is missing :(

**Comment by kristijanhusak** [comment]
@schursin thanks!

**Pull request merged**
