### PR TITLE
Add field error class

### PR DESCRIPTION
**Pull request by n7olkachev**

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@n7olkachev can you explain a bit what is this PR for?

**Comment by n7olkachev** [comment]
My bad, sorry.
Yep, it's useful because of bootstrap 4 validation, where you need to add `is-invalid` class on an `input` itself.

**Comment by kristijanhusak** [comment]
Please update the default config to include that field class, set it to be empty string by default.

**Comment by n7olkachev** [comment]
@kristijanhusak done

**Comment by kristijanhusak** [comment]
Thanks!

**Pull request merged**
