### PR TITLE
Load error and help_block from package namespace instead of hardcoded path

### PR DESCRIPTION
**Pull request by azisyus**
This PR fixes a bug caused by my last PR (#607), view paths generated from package's namespace so we can use most relevant view.

### CODE REVIEW

**Comment by rudiedirkx** [comment]
Does that work if I convert my views to Twig or Blade? I think `view($path)` will find any extension view, not just `.php`, and you can't just include a Twig or Blade file into PHP.

**Comment by rudiedirkx** [comment]
I think the functions can be dumber. Just check if the `.php` file exists in the configured folder. I don't know where the folder is configed, but I'm sure `app()` or `view()` or `config('view')` knows.

**Comment by azisyus** [comment]
`view($path)` doesn't load files with `*.twig` extension so you can't use that template engine but `*.blade.php` is fine because `view($path)` probably checks for that and it's only valid for `.blade.php` and `.php` files. Does this package promises usage of another template engine?

**Comment by rudiedirkx** [comment]
> view($path) doesn't load files with *.twig extension so you can't use that template engine

My projects use Twig, so it does. That's how Laravel works. Any engine works. Laravel can render all those supported types, but php can't just include all those types.

Since Laravel supports any tpl engine, we must at least make sure it doesn't break. We don't have to look for `help_block.twig` and render it correctly IMO, but we must not include it like it's a `.php` file.

I would hard-check to only accept `.php`, not even `.blade.php`. Those files come from this package, so we support that. All others meh.

**Comment by azisyus** [comment]
>  Laravel can render all those supported types, but php can't just include all those types.

That makes sense, thanks for you patience.

**Comment by rudiedirkx** [comment]
I like it!

**Pull request merged**
