### PR TITLE
Laravel 5.3 support

### PR DESCRIPTION
**Pull request by max-kovpak**
The lists method on the Collection, query builder and Eloquent query builder objects has been renamed to pluck. The method signature remains the same.

### CODE REVIEW

**Comment by max-kovpak** [comment]
And you must change laravel version or hhvm version in travis. Because laravel/framework require php >=5.6.4. Check tests, you will see exception:

> ErrorException: Use of undefined constant ARRAY_FILTER_USE_BOTH - assumed 'ARRAY_FILTER_USE_BOTH'

Constant ARRAY_FILTER_USE_BOTH was added in php 5.6.0

**Comment by kristijanhusak** [comment]
Thanks for the PR. Can you update both travis.yml and package.json to allow only php 5.6+ ? Thanks!

**Comment by max-kovpak** [comment]
Updated

**Comment by kristijanhusak** [comment]
Great. Thanks!

**Pull request merged**
