### PR TITLE
Customizable classes by config.

### PR DESCRIPTION
**Pull request by ukeloop**
Customizable classes by config.

e.g.

```php
'form_builder' => \Kris\LaravelFormBuilder\FormBuilder::class,
'helper' => \App\Form\MyFormHelper::class,
```

```php
class MyFormHelper extend FormHelper
{
    public function mergeOptions(array $targetOptions, array $sourceOptions)
    {
        return $targetOptions + $sourceOptions;
    }
}
```

### CODE REVIEW

**Comment by rudiedirkx** [comment]
- Definitely don't use `config()` in a service provider.
- Don't **remove** the standard alias `Kris\LaravelFormBuilder\FormBuilder`. You can add the custom form builder class as alias, but don't remove the package form builder class alias,

**Comment by ukeloop** [comment]
What are the reasons for them? Many libraries have provided hacks for them.

If I mode helper method, I need override the service provider.

**Comment by rudiedirkx** [comment]
Reasons for what? Hacks for what?

You shouldn't use `config()` in a SP because you have `$this->app['config']` right there.

You shouldn't remove the standard alias, only add others, because others might use that standard alias, so it still has to work. So the `$this->app->alias()` bit should check if the configed class is the standard class, and then add 1 or 2 aliases.

**Comment by rudiedirkx** [comment]
That's not what I meant. My worry is that there's no alias for `Kris\LaravelFormBuilder\FormBuilder` if you change the form builder class to `App\MyFormBuilder`. `laravel-form-builder` and `App\MyFormBuilder` will work, but `Kris\LaravelFormBuilder\FormBuilder` won't work anymore (**I think**) because it's not an alias anymore. Any package will expect `Kris\LaravelFormBuilder\FormBuilder` to work, because it doesn't know if the dev changed the form builder class (or even that that's possible now).

I'm gonna do some tests with this branch.

**Comment by rudiedirkx** [comment]
Yes, the standard alias is 'broken'. You can't 'constructor inject' with the container's `Kris\LaravelFormBuilder\FormBuilder` if you've overridden the form builder class.

And you should add `_class` to the config names, so we can also do this for the form class (for plain forms). `form` is already taken for the template.

**Comment by rudiedirkx** [comment]
So it should

    $this->app->alias($abstract, $formBuilder);
    $this->app->alias($abstract, FormBuilder::class);

and then it doesn't matter how you ask the DIC for the form builder: 'laravel-form-builder', `Kris\LaravelFormBuilder\FormBuilder` and `App\MyFormBuilder` will all get the DIC's `App\MyFormBuilder` object.

And the same for the helper.

And I would love it if you did the form class too =) FormBuilder already has a `setFormClass()` method.

**Comment by rudiedirkx** [comment]
And your tests :heart_eyes: could test for that:

```
some_container_injected_function(Kris\FormBuilder $forms1, MyFormBuilder $forms2) {
  $forms1 === $forms2 === app('kris-form-builder');
}
```

**Review by rudiedirkx — CHANGES_REQUESTED** [review]
- Call the configs `form_helper_class`, `form_builder_class` (and `form_class`? if you want)
    - Use `form_class` to call form builder's `setFormClass()` from the SP. Or this could be another PR.
- Add **both** aliases if the class was changed to something else, not just the new alias

**Review by rudiedirkx — CHANGES_REQUESTED** [review]
Test `it_register()` doesn't test anything. All the tested binds are already bound in `$this->app`, even without the `$provider` bit, so you could just remove that and it'd still pass.

**Comment by rudiedirkx** [comment]
This `FormBuilderServiceProviderTest` is more useful. It overrides the `form_builder_class` config and tests if all the dependency injection works, with standard and custom abstracts.

**Comment by ukeloop** [comment]
Thanks for fixing my codes.

**Comment by rudiedirkx** [comment]
This code will have your name attached to it too ;) Are you okay with the current branch?

**Comment by ukeloop** [comment]
Of course. Thanks for reviewing and fixing my PR.

**Pull request merged**
