### PR TITLE
Added a new method `Form::group`.

### PR DESCRIPTION
**Pull request by yaquawa**
Alternative PR to #580 which implemented a new `group` method.
It was branched from #577 you can compare the changes at [here](https://github.com/yaquawa/laravel-form-builder/compare/e0951c54f5ac7d581b9bb49155ee62dbfc7c8e6c...yaquawa:field_group)
(I'm going to rebase this on master once #577 get merged)

## Usage

```php
$form
    ->add('foo')
    ->group(function (FieldGroup $fieldGroup) {
        $fieldGroup->add('bar');
        $fieldGroup->add('foobar');
        $fieldGroup->group(function (FieldGroup $subFieldGroup) {
            $subFieldGroup->add('sub_bar');
            $subFieldGroup->add('sub_foobar');
        });
    })
    ->group(function (FieldGroup $fieldGroup) {
        $fieldGroup->add('baz');
    })
    ->add('qux');
```

Outputs:
```html
<form method="GET" action="http://localhost" accept-charset="UTF-8">
    <div class="form-group">
        <label for="foo" class="control-label">Foo</label>
        <input class="form-control" name="foo" type="text" id="foo">
    </div>
    <fieldset class="form-group">
        <div class="form-group">
            <label for="bar" class="control-label">Bar</label>
            <input class="form-control" name="bar" type="text" id="bar">
        </div>
        <div class="form-group">
            <label for="foobar" class="control-label">Foobar</label>
            <input class="form-control" name="foobar" type="text" id="foobar">
        </div>
        <fieldset class="form-group">
            <div class="form-group">
                <label for="sub_bar" class="control-label">Sub bar</label>
                <input class="form-control" name="sub_bar" type="text" id="sub_bar">
            </div>
            <div class="form-group">
                <label for="sub_foobar" class="control-label">Sub foobar</label>
                <input class="form-control" name="sub_foobar" type="text" id="sub_foobar">
            </div>
        </fieldset>
    </fieldset>
    <fieldset class="form-group">
        <div class="form-group">
            <label for="baz" class="control-label">Baz</label>
            <input class="form-control" name="baz" type="text" id="baz">
        </div>
    </fieldset>
    <div class="form-group">
        <label for="qux" class="control-label">Qux</label>
        <input class="form-control" name="qux" type="text" id="qux">
    </div>
</form>
```

### CODE REVIEW

**Comment by rudiedirkx** [comment]
You removed `if( ! in_array($field->getName(), $exclude) )`?

Why make a form copy, `compose()` its fields and discard it? Why not immediately add fields to the real form?

It feels a bit weird. It's like a `ParentType`, but done differently. `ParentType` should (be able to) do this. We don't need another kinda-`ParentType`. #580 seems perfect for a separate package. Why this?

I'm sorry. I feel like an asshole. I still don't get it, so I keep bitching. Templates, man =) They're so easy.

**Comment by yaquawa** [comment]
@rudiedirkx Thanks for reviewing👍🏼
> You removed if( ! in_array($field->getName(), $exclude) )?

Yes, because I don't think this was even be used as I asked at #581...  I can bring it back if needed. @kristijanhusak What do you think?

> Why make a form copy, compose() its fields and discard it?

The cloned form object is for storing the added fields in the group. 

> Why not immediately add fields to the real form?

Yes, the added fields were [added to the real form too](https://github.com/kristijanhusak/laravel-form-builder/pull/582/commits/ef6029d2a79665b9b2540f5bbfabdd29c86b618e#diff-7f17d71f56dd1175c49875c83e9adc04R316).

> It feels a bit weird. It's like a ParentType, but done differently. ParentType should (be able to) do this. We don't need another kinda-`ParentType`. #580 seems perfect for a separate package. Why this?

I've done it by mimicking the `ParentType` on #580. At first I thought that's the way to go, but as @kristijanhusak said:

> Let's try to do something that will work in similar way as compose, but to allow setting up the container.

then I realized that making it looks like a parent can be very confusing (semantically)... keeping the hierarchy as it is is more intuitively(so we can `remove` or `modify` the fields in the group directly).

> I still don't get it, so I keep bitching. Templates, man =) They're so easy.

Hmm.. I like this package because I don't have to think about views.. I think that's the beauty of this package. And as I said before, if you are going to use a template instead, it comes quite messy very soon if you start using group in collection or child form field type. I'd like just `form($form)` and forget anything else. Again that's the reason I like this package. Grouping fields is very common, why not..?

**Comment by kristijanhusak** [comment]
@yaquawa please clean up the PR so I can see only code relevant to this PR. I don't want to see rules PR here.

**Comment by yaquawa** [comment]
@kristijanhusak You can see the diff [here](https://github.com/yaquawa/laravel-form-builder/compare/e0951c54f5ac7d581b9bb49155ee62dbfc7c8e6c...yaquawa:field_group), I used some phpunit methods that not exists in the legacy version of phpunit before #577.

**Comment by kristijanhusak** [comment]
@yaquawa lets then have a PR that only updates phpunit so we can split all these PRs that you create to have only code related to the PR. I can't go through 20 files for each PR, i have no idea what was changed.

**Comment by yaquawa** [comment]
Hi @kristijanhusak , I mean you can see the changes by comparing the #577 with this branch:

https://github.com/yaquawa/laravel-form-builder/compare/e0951c54f5ac7d581b9bb49155ee62dbfc7c8e6c...yaquawa:field_group

What you see is the same result even I created another PR to update phpunit.

Then after #577 got merged, this can be rebased on it.

**Comment by rudiedirkx** [comment]
Yeah @kristijanhusak let's merge [#577](https://github.com/kristijanhusak/laravel-form-builder/pull/577#issuecomment-584140269) =p

**Comment by yaquawa** [comment]
Thanks @rudiedirkx !
I've just rebased this PR onto the master👍🏼

**Comment by rudiedirkx** [comment]
I don't know how to retry checks (Travis). Can Github do that?

**Comment by kristijanhusak** [comment]
@rudiedirkx i retried it on travis.

**Comment by rudiedirkx** [comment]
It seems to retry with the same config =) Which makes sense, because that's the config in this PR.

@yaquawa Can you do another rebase from `master`? That will take the right config and trigger tests.

**Comment by yaquawa** [comment]
@rudiedirkx Done!

**Comment by rudiedirkx** [comment]
Aw yeah look at that continuous integrationness

> All checks have passed
> 11 successful checks

`11` is just twice as much as `1`, right?

The PR is for @kristijanhusak to decide though. I'm against, but only slightly.

**Comment by kristijanhusak** [comment]
@yaquawa this just looks like something that is used to avoid adding any custom rendering to view with some child forms. Intention of the package was never to make a form and just use `form($form)` all the time. It is possible sometimes, but for complicated forms, you should use other view helpers to achieve what you need. 
As the title of the package says, Symfony like form builder. Symfony form builder requires same amount, or even more logic in the views than this package.

If you really need this functionality, you can always add it as a custom field and just use it wherever you need.
I appreciate the effort to add this, but I think it's out of scope since it can be added as a customization.

**Comment by yaquawa** [comment]
> this just looks like something that is used to avoid adding any custom rendering to view with some child forms.

You can specify a custom template for the group too.

**Comment by SanderMuller** [comment]
I like this idea for something like bootstrap tabs, where you organize a form in groups and then in the template render each group in it's separate tab. 👍

**Comment by mertasan** [comment]
This is exactly what I need. I'm having trouble making a template like the one below. Of course I can do it using the templates. However, if I were to do it manually, I wouldn't prefer to use a form builder. Please consider this issue.

```html
<div class="form-group row">
    <div class="col-lg-4">
        <input>
    </div>
    <div class="col-lg-4">
        <input>
    </div>
</div>
<div class="form-group row">
    <div class="col-lg-4">
        <input>
    </div>
    <div class="col-lg-4">
        <input>
    </div>
</div>
```

**Comment by MahdiPishguy** [comment]
@mertasan could you resolve your problem?

**Pull request closed without merging**
